kind: Service                             
apiVersion: v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  ports:
    - port: 8080                               
      targetPort: 81                    
      nodePort: 31201
  selector:
    app: devops                    
  type: LoadBalancer