kind: Service                             
apiVersion: v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  selector:
    app: devops                    
  type: NodePort